[tool.poetry]
name = "test-platform-server"
version = "0.1.0"
description = ""
authors = ["Kelvin.Ye <testmankelvin@163.com>"]

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true
#secondary = true

[[tool.poetry.source]]
name = "baidu"
url = "https://mirror.baidu.com/pypi/simple/"
#default = true
secondary = true

[tool.poetry.dependencies]
python = "^3.6"
flask = "^1.1.2"
flask-socketio = "^4.3.1"
flask-sqlalchemy = "^2.4.4"
flask-migrate = "^2.5.3"
flask-monitoringdashboard = "^3.1.0"
flasgger = "^0.9.5"
orjson = "^3.4.1"
jsonpath = "^0.82"
pyjwt = "^1.7.1"
pytest = "^5.4.3"
pytest-html = "^2.1.1"
gunicorn = "^20.0.4"
gevent = "^20.0.9"
requests = "^2.24.0"
elasticsearch = "^7.9.1"
celery = "^5.0.1"
pycryptodome = "3.9.8"
numpy = "^1.19.3"
flake8 = "*"
yapf = "*"
uwsgi = { version = "2.0.19.1", markers = "platform_system == 'Linux'" }
flask-graphql = "^2.0.1"
graphene = "^2.1.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
