[tool.poetry]
name = "qa-cloud-backend"
version = "0.1.0"
description = ""
authors = ["Kelvin.Ye <testmankelvin@163.com>"]

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[tool.poetry.dependencies]
python = "^3.8"
flask = "2.0.1"
flask-socketio = "5.1.0"
flask-sqlalchemy = "2.5.1"
flask-migrate = "3.0.1"
orjson = "3.5.4"
jsonpath = "0.82"
pydantic = "1.8.2"
pyjwt = { version = "2.1.0", extras=["crypto"] }
pycryptodome = "3.10.1"
python-dotenv = "0.18.0"
gevent = "21.1.2"
gevent-websocket = "0.10.1"
gunicorn = { version = "*", markers = "platform_system == 'Linux'" }
uwsgi = { version = "*", markers = "platform_system == 'Linux'" }
pymeter = {path = "../pymeter", develop = true}

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-html = "*"
flake8 = "*"
yapf = "*"
isort = "*"

[build-system]
requires = [
    "setuptools!=50.0",
    "poetry>=0.12"
]
build-backend = "poetry.masonry.api"

[tool.isort]
profile = "pycharm"
line_length = 120
force_single_line = true
multi_line_output = 3
