[tool.poetry]
name = "appui-automator"
version = "0.1.0"
description = ""
authors = ["Kelvin.Ye <testmankelvin@163.com>"]

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[[tool.poetry.source]]
name = "douban"
url = "https://pypi.douban.com/simple/"
secondary = true

[tool.poetry.dependencies]
python = "^3.6"
flask្្= "1.1.2"
flask-socketio = "4.2.1"
flask-sqlalchemy = "2.4.1"
flasgger = "0.9.3"
click = "7.0"
orjson = "^2.6.2"
jsonpath = "0.82"
pyjwt = "1.7.1"
pytest = "^5.4.1"
pytest-html = "^2.1.1"
pytest-dependency = "^0.5.1"
pytest-ordering = "^0.6"
pytest-sugar = "^0.9.2"
pytest-rerunfailures = "^9.1"
allure-pytest = "^2.8.12"
gunicorn = "20.0.4"
gevent = "1.4.0"
requests = "2.22.0"
elasticsearch = "7.6.0"
flask-migrate = "2.5.3"
celery = "4.4.2"
pycryptodome = "^3.9.8"
uwsgi = "*"
flake8 = "*"
yapf = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
