[tool.poetry]
name = "qa-cloud-backend"
version = "0.1.0"
description = ""
authors = ["Kelvin.Ye <testmankelvin@163.com>"]

# [[tool.poetry.source]]
# name = "aliyun"
# url = "https://mirrors.aliyun.com/pypi/simple/"
# default = true

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[tool.poetry.dependencies]
python = "^3.8"
# Flask
flask = "2.0.2"
flask-sqlalchemy = "2.5.1"
flask-socketio = "5.1.1"
flask-migrate = "3.1.0"
# Json
orjson = "3.6.5"
jsonpath = "0.82"
# Encryption
pyjwt = { version = "2.3.0", extras=["crypto"] }
pycryptodome = "3.12.0"
# Data validation
pydantic = "1.8.2"
# Database
psycopg2 = "2.9.2"
# Coroutine
gevent = "21.8.0"
# Deployment
uwsgi = { version = "*", markers = "sys_platform=='linux' or sys_platform=='darwin" }
#supervisor = { version = "*", markers = "sys_platform == 'linux'" }
# 私仓依赖
pymeter = { path = "../pymeter", develop = true }
# Environment
python-dotenv = "0.19.1"
environs = "9.3.4"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-html = "*"
flake8 = "*"
yapf = "*"
isort = "*"

[build-system]
requires = [
    "setuptools!=50.0",
    "poetry>=0.12"
]
build-backend = "poetry.masonry.api"

[tool.isort]
profile = "pycharm"
line_length = 120
force_single_line = true
multi_line_output = 3
skip_glob = ["migrations/*"]
